/**
 * Ayna Module Types
 * Medusa v2 compliant type definitions for the Ayna AI module
 */

import { MedusaContainer } from "@medusajs/framework/types"

// ============================================================================
// MEMORY TYPES
// ============================================================================

export interface MemoryTruth {
    id: string
    actor: string
    action: string
    data: Record<string, any>
    created_at: Date
}

export interface MemoryInsight {
    id: string
    entity_id: string
    key: string
    value: string
    type: string
    created_at: Date
    updated_at: Date
}

export interface MemoryConscience {
    id: string
    proposed_action: string
    verdict: "ALLOW" | "DENY" | "WARN"
    reasoning: string
    created_at: Date
}

export interface Mission {
    id: string
    title: string
    description: string
    status: "active" | "completed" | "cancelled"
    created_at: Date
    updated_at: Date
}

// ============================================================================
// TOOL TYPES
// ============================================================================

export interface IAynaTool {
    name: string
    description: string
    schema: ToolSchema
    execute(args: any, container?: MedusaContainer): Promise<any>
}

export interface ToolSchema {
    type: "object"
    properties: Record<string, ToolProperty>
    required?: string[]
}

export interface ToolProperty {
    type: "string" | "number" | "boolean" | "array" | "object"
    description: string
    enum?: string[]
}

// ============================================================================
// PRODUCT SEARCH TYPES
// ============================================================================

export interface ProductSearchResult {
    title: string
    price: string
    description: string
    link: string
    inventory: {
        available: number
        status: "IN_STOCK" | "OUT_OF_STOCK"
        honesty_verified: boolean
    }
    honesty_note: string | null
}

export interface ProductSearchResponse {
    message: string
    products?: ProductSearchResult[]
    errors?: string[]
    error?: string
    details?: string
}

// ============================================================================
// MESSAGE PROCESSING TYPES
// ============================================================================

export interface ProcessMessageOptions {
    entityId?: string
    container?: MedusaContainer
}

export interface ProcessMessageResponse {
    response: string
    debug: {
        model?: string
        tool_used?: boolean
        iterations?: number
        customerGroup?: string
        error?: string
    }
}

// ============================================================================
// SERVICE INTERFACE
// ============================================================================

export interface IAynaService {
    // Message Processing
    processMessage(message: string, options?: string | ProcessMessageOptions): Promise<ProcessMessageResponse>

    // Memory Operations
    recordTruth(actor: string, action: string, data: any): Promise<MemoryTruth>
    storeInsight(entityId: string, key: string, value: string, type?: string): Promise<MemoryInsight>

    // CRUD (auto-generated by MedusaService)
    listMemoryTruths(filters?: any): Promise<MemoryTruth[]>
    listMemoryInsights(filters?: any): Promise<MemoryInsight[]>
    listMemoryConsciences(filters?: any): Promise<MemoryConscience[]>
    createMemoryTruths(data: Partial<MemoryTruth>): Promise<MemoryTruth[]>
    createMemoryInsights(data: Partial<MemoryInsight>): Promise<MemoryInsight[]>
    createMemoryConsciences(data: Partial<MemoryConscience>): Promise<MemoryConscience[]>
}

// ============================================================================
// CONTENT CREATOR TOOL TYPES
// ============================================================================

export interface CreateBlogPostArgs {
    title: string
    slug: string
    content: string
    image?: string
    status: "draft" | "published"
}

export interface CreateBlogPostResult {
    success: boolean
    message?: string
    post_id?: string
    slug?: string
    url?: string
    error?: string
    suggestion?: string
}
